version: "3"

services:
  chain-tx-enclave:
    image: "${CHAIN_TX_ENCLAVE_DOCKER_IMAGE:-integration-tests-chain-tx-enclave}"
    volumes:
      - "${ENCLAVE_DIRECTORY}:/.storage"
    devices:
      - "${DOCKER_SGX_DEVICE_BINDING}"
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
      TX_ENCLAVE_STORAGE: /.storage
  tendermint:
    image: "tendermint/tendermint:v${TENDERMINT_VERSION:-0.32.0}"
    command: node --proxy_app=chain-abci:26658 --rpc.laddr=tcp://0.0.0.0:26657 --consensus.create_empty_blocks=true
    volumes:
      - "${TENDERMINT_DIRECTORY}:/tendermint"
    ports:
      - ${TENDERMINT_RPC_PORT:-26657}:26657
  chain-abci:
    image: "${CHAIN_DOCKER_IMAGE:-integration-tests-chain}"
    command: "/usr/bin/chain-abci --host=0.0.0.0 --port=26658 --chain_id=${CHAIN_ID} --genesis_app_hash=${APP_HASH} --enclave_server=tcp://chain-tx-enclave:25933 --data=/.storage"
    volumes:
      - "${CHAIN_ABCI_DIRECTORY}:/.storage"
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
  client-rpc:
    image: "${CHAIN_DOCKER_IMAGE:-integration-tests-chain}"
    command: /usr/bin/wait-for-it.sh tendermint:26657 --timeout=60 --strict -- /usr/bin/client-rpc --host=0.0.0.0 --port=26659 --chain-id=${CHAIN_ID} --storage-dir=/.storage --websocket-url=ws://tendermint:26657/websocket
    volumes:
      - "${WALLET_STORAGE_DIRECTORY}:/.storage"
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
    ports:
      - ${CLIENT_RPC_PORT:-26659}:26659
